# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: users_api.proto for package ''

module UsersApi
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'UsersApi'

    rpc :GetUser, UserRequest, UserResponse
  end

  Stub = Service.rpc_stub_class
end
