# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users_api.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "UserRequest" do
    optional :email, :string, 1
  end
  add_message "UserResponse" do
    optional :first_name, :string, 1
    optional :last_name, :string, 2
    optional :email, :string, 3
  end
end

UserRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("UserRequest").msgclass
UserResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("UserResponse").msgclass
